name: ercoin_wallet
description: Ercoin wallet.

version: 1.0.0+1

environment:
  sdk: ^2.7.0

dependencies:
  flutter:
    sdk: flutter
  sqflite:
  path_provider: any
  cupertino_icons: ^0.1.2
  shared_preferences: any
  random_string: any
  rflutter_alert: ^1.0.3
  flutter_sodium: 0.0.10
  convert: any
  utf: 0.9.0+5
  http: ^0.12.0+2
  crypto: 2.1.3
  folder_picker: 0.3.0
  file_picker: 1.4.2
  qr_flutter: ^3.1.0
  barcode_scan: 1.0.0
  intl: ^0.16.0
  injector: 1.0.8
  equatable: ^1.0.0
  base58check: 1.0.1
  test:

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  flutter_sodium:
    git:
      url: https://github.com/kubawal/flutter_sodium
      ref: master


flutter:
  uses-material-design: true


